theme: jekyll-theme-cayman


title: "湖北/武汉红十字 云监工平台"

#repository: "https://github.com/WeileiZeng/red-cross"
repo: "https://github.com/weileizeng/red-cross"

google_analytics: UA-155170936-2

#count total number of visitors
visitor_count: 1693
visitor_count_timestamp: Feb 6, 16:00PM


github:
  is_project_page: false

  
