theme: jekyll-theme-cayman


title: "湖北/武汉红十字 云监工平台"
#repository: "https://github.com/WeileiZeng/red-cross"
repo: "https://github.com/weileizeng/red-cross"

google_analytics: UA-155170936-2

#count total number of visitors
visitor_count: 1427
visitor_count_timestamp: Feb 5, 16:00AM


github:
  is_project_page: false

show_navigations: true

navigations:
  - name: test
    url: tes
  - name:   信息录入
    url: https://weileizeng.github.io/red-cross/CONTRIBUTE


  
